past_hours: 15
bancolombia_fingerprint: True
bbva_fingerprint: True
retry: 2
x_max: 720
y_max: 1600
AUT_USER: 749278100
P2P_SCREENSHOT_BOT : '5626108765:AAEJdzS1_Zmu5uOsDu-HItPgvYdfcDFzk3I'
P2P_DASHBOARD_BOT : '5572206324:AAG_LVN8xLdFkxf4FY9IFwCmZMlV0gDWJyg'
google_drive_parent: '1T3kw9-qer4o_zhlCOFt4-_gLaxxv8xh7'
enrolling_account_message: "En este momento procedemos a inscribir tu cuenta"
enrolling_account_done_message: "!! Se ha inscrito correctamente tu cuenta !! "
enrolling_account_fail_message: "upps Fallo la inscripcion, parece que los datos no son correctos, porfavor verificar "
process_payment_message: "Procedemos a hacer el envio del dinero 💵"
process_payment_done: "El pago se ha realizado correctamente 🥳🥳🥳🥳"
process_payment_fail: " upps la plataforma de bancolombia esta caida en este momento, en 5 minutos reintentaremos tu pago."
message_for_drive: "En este link encuentras el comprobante de pago, copialo y pegalo, es un drive asi que lo puedes descargar."
thanks_message: "Gracias por comerciar con nosotros 😊, no olvides liberar."