version: '3.6'

services:
  sparklab-db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sparklab-db
    volumes:
      - sparklab_db_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  sparklab-api:
    build: .
    volumes:
      - sparklab_db_postgres_data:/var/lib/postgresql/data/
    env_file:
      - api.env
    ports:
      - 80:8000
    depends_on:
      - sparklab-db
volumes:
  sparklab_db_postgres_data: