# Generated by Django 4.1.3 on 2022-12-04 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "binance_id",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("pay_id", models.CharField(max_length=500)),
                ("amount", models.CharField(max_length=500)),
                ("usdt_price", models.CharField(max_length=500)),
                ("is_contact", models.BooleanField(blank=True, null=True)),
                ("account", models.CharField(max_length=500)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="When Created"
                    ),
                ),
                ("status", models.CharField(default="created", max_length=500)),
                ("fail_retry", models.IntegerField(default=0)),
                (
                    "subscribe",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "account_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.accounttype",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.bank"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.documenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
