# Generated by Django 4.1 on 2022-08-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('binance_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=500)),
                ('is_contact', models.BooleanField(blank=True, null=True)),
                ('account', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('document_number', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='created', max_length=500)),
                ('fail_retry', models.IntegerField(default=0)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.bank')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.documenttype')),
            ],
        ),
    ]
