# Generated by Django 4.0.6 on 2022-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_account_type_alter_order_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When Created'),
        ),
    ]
