# Generated by Django 4.1.3 on 2023-01-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_amounttobuy_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='min_limit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='use_min_limit',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
