# Generated by Django 4.1 on 2022-10-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usdt_price',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
