# Generated by Django 4.0.6 on 2022-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_usdt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
