# Generated by Django 4.0.6 on 2022-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
